functionsDirectory = "/home/reynald/Reynald_Trading/app/netlify/functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/reynald/Reynald_Trading/app/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/reynald/Reynald_Trading/app"
command = "npm run build"
functions = "/home/reynald/Reynald_Trading/app/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]